language: go

go:
    - 1.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs
    - go get -u ./...
    - go get -u -d -tags=js ./...

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - go test github.com/FlashbackSRS/flashback-model github.com/FlashbackSRS/flashback-model/test
    - gopherjs test --tags=disableunsafe github.com/FlashbackSRS/flashback-model github.com/FlashbackSRS/flashback-model/test
